defaults:
  - inference: latest
  - _self_

# A40 GPU EXTREME optimization for maximum speed
# Pushes A40's limits with aggressive settings

model:
  model_id: meta-llama/Llama-3.2-1B-Instruct
  use_dora: false
  seq_len: 128  # Very short sequences for maximum speed

dataset:
  dataset_id: izumi-lab/llm-japanese-dataset
  dataset_split: "train[:1%]"
  val_ratio: 0.1

training:
  lr: 5e-5  # Higher learning rate for faster convergence
  batch_size: 128  # Very large batch size for A40
  gradient_accumulation_steps: 1  # No accumulation needed
  epochs: 1  # Single epoch for quick testing
  seed: 42
  # epoch-based evaluation for maximum speed
  early_stopping_patience: 2

peft:
  r: 8  # Smaller rank for faster training
  lora_alpha: 16  # Proportionally smaller alpha
  lora_dropout: 0.05  # Lower dropout
  target_modules:
    - q_proj
    - v_proj
    # Only 2 modules for maximum speed

output:
  base_output_dir: ./outputs
  experiment_name: a40-extreme
  # All other paths will be auto-generated in the structured format:
  # ./outputs/experiments/{experiment_name}/runs/{run_id}/
  #   ├── artifacts/adapter/
  #   ├── artifacts/tokenizer/
  #   ├── artifacts/merged/
  #   ├── logs/
  #   └── metadata/

logging:
  report_to: tensorboard
  project_name: llama-lora-a40-extreme